<?xml version="1.0" encoding="UTF-8"?>
<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.java.desktop</groupId>
    <artifactId>jawt-ffm-shared</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <parent>
        <groupId>org.java.desktop</groupId>
        <artifactId>ffm-awt-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <testSourceDirectory>${project.basedir}/src/test</testSourceDirectory>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <compilerArgs>
                        <arg>-h</arg>
                        <arg>${project.build.directory}/generated-sources/c</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <version>1.0.0</version>
                <extensions>true</extensions>
                <configuration>
                    <sources>
                        <source>
                            <directory>${project.basedir}/src/main/c</directory>
                            <includes>
                                <include>**/*.c</include>
                                <include>**/*.m</include>
                            </includes>
                        </source>
                    </sources>
                    <compilerStartOptions>
                        <compilerStartOption>-I${project.build.directory}/generated-sources/c</compilerStartOption>
                        <compilerStartOption>-I${java.home}/include</compilerStartOption>
                        <compilerStartOption>-I${java.home}/include/darwin</compilerStartOption>
                        <compilerStartOption>-fPIC</compilerStartOption>
                    </compilerStartOptions>
                    <linkerStartOptions>
                        <linkerStartOption>-dynamiclib</linkerStartOption>
                        <linkerStartOption>-L${java.home}/lib</linkerStartOption>
                        <linkerStartOption>-ljawt</linkerStartOption>
                        <linkerStartOption>-framework</linkerStartOption>
                        <linkerStartOption>OpenGL</linkerStartOption>
                        <linkerStartOption>-framework</linkerStartOption>
                        <linkerStartOption>Cocoa</linkerStartOption>
                    </linkerStartOptions>
                    <linkerOutputDirectory>${project.build.directory}/native</linkerOutputDirectory>
                    <linkerFinalName>libjawtffmjni</linkerFinalName>
                    <linkerFinalNameExt>dylib</linkerFinalNameExt>
                    <attach>false</attach>
                </configuration>
                <executions>
                    <execution>
                        <id>build-jni-library</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>initialize</goal>
                            <goal>compile</goal>
                            <goal>link</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.2</version>
                <configuration>
                    <useModulePath>false</useModulePath>
                    <argLine>--enable-native-access=ALL-UNNAMED</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>