<?xml version="1.0" encoding="UTF-8"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.java.desktop</groupId>
    <artifactId>ffm-awt-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        
        <module>JAWT-FFM-SHARED</module>
        
        <module>JAWT-FFM-MACOS</module>
        <module>JAWT-FFM-UNIX</module>
        <module>JAWT-FFM-WINDOWS</module>
    </modules>

    <properties>
        <maven.compiler.source>22</maven.compiler.source>
        <maven.compiler.target>22</maven.compiler.target>
        <junit.jupiter.version>5.12.2</junit.jupiter.version>
        <lwjgl.version>3.3.6</lwjgl.version>
    </properties>

</project>