<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>macos-gl</artifactId>
    <version>1.0-SNAPSHOT</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <version>1.0.0</version>
                <extensions>true</extensions>
                <configuration>
                    <sources>
                        <source>
                            <directory>${project.basedir}/src/main/c</directory>
                            <includes>
                                <include>**/*.c</include>
                                <include>**/*.m</include>
                            </includes>
                        </source>
                    </sources>
                    <compilerStartOptions>
                        <compilerStartOption>-I${java.home}/include</compilerStartOption>
                        <compilerStartOption>-I${java.home}/include/darwin</compilerStartOption>
                        <compilerStartOption>-fPIC</compilerStartOption>
                    </compilerStartOptions>
                    <linkerStartOptions>
                        <linkerStartOption>-dynamiclib</linkerStartOption>
                        <linkerStartOption>-L${java.home}/lib</linkerStartOption>
                        <linkerStartOption>-ljawt</linkerStartOption>
                        <linkerStartOption>-framework</linkerStartOption>
                        <linkerStartOption>Cocoa</linkerStartOption>
                        <linkerStartOption>-framework</linkerStartOption>
                        <linkerStartOption>QuartzCore</linkerStartOption>
                        <linkerStartOption>-framework</linkerStartOption>
                        <linkerStartOption>OpenGL</linkerStartOption>
                    </linkerStartOptions>
                    <linkerOutputDirectory>${project.build.directory}/native</linkerOutputDirectory>
                    <linkerFinalName>libswinggl</linkerFinalName>
                    <linkerFinalNameExt>dylib</linkerFinalNameExt>
                    <attach>false</attach>
                </configuration>
                <executions>
                    <execution>
                        <id>build-native-library</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>initialize</goal>
                            <goal>compile</goal>
                            <goal>link</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            
        </plugins>
    </build>
</project>